image:  repo.htl-md.schule:5003/gradle:8.6.0-jdk21-alpine

include:
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml
  - template: Jobs/SAST.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml
  - component: gitlab.onelitefeather.dev/dungeon/ci-components/gradle-publish@0.0.4
variables:
  SECURE_ANALYZERS_PREFIX: "${HTL_NEXUS_PROXY}/security-products"
  GRADLE_IMAGE: "${HTL_NEXUS_PROXY}/gradle:8.10.0-jdk21"
